name: "jagel.net LDAP-IMAP-Bridge"
description: "A bridge to authenticate LDAP requests against the jagel.net IMAP server."
version: "1.0.0"
slug: "ldap-imap-bridge"
init: false
startup: system
boot: auto
arch:
  - amd64
  - i386
ports:
  1389/tcp: 1389
ports_description:
  1389/tcp: LDAP Port
map:
  - type: addon_config
    read_only: False
options:
  system_packages: []
  init_commands: []
schema:
  system_packages:
    - str
  init_commands:
    - str