name: "TVHeadend"
description: "TV streaming server and recorder."
version: "amd64-latest"
#version: "1.0.0"
slug: "tvheadend"
init: false
startup: system
boot: manual
arch:
  # - aarch64
  - amd64
host_network: true
ports:
  9981/tcp: 9981
  9982/tcp: 9982
ports_description:
  9981/tcp: TVH Web Interface
  9982/tcp: TVH HTSP
webui: "http://[HOST]:[PORT:9981]/"
devices:
  - /dev/dvb
  - /dev/dri
map:
  # Image uses /config
  - type: addon_config
    read_only: False
    path: /config
  # Image uses /recordings
  - type: media
    read_only: False
    path: /recordings
environment:
  RUN_OPTS: "--nobackup"
  PGID: "999"
  TZ: "Europe/Berlin"
# image: lscr.io/linuxserver/tvheadend <- shall be the path to the registry where the externally build HA docker image is stored
image: lscr.io/linuxserver/tvheadend
codenotary: dev@jagel.net